Name=zero-lliurex-kdenlive
Name[es]=Configurador Kdenlive
Name[ca@valencia]=Configurador Kdenlive
Name[qcv]=Configurador Kdenlive
Name[ca_ES]=Configurador Kdenlive
Comment=Configures Kdenlive AI plugins
Comment[es]=Configurador de los conectores IA en Kdenlive
Comment[ca@valencia]=Configurador dels connectors d'IA al Kdenlive
Comment[qcv]=Configurador dels connectors d'IA al Kdenlive
Comment[ca_ES]=Configurador dels connectors d'IA al Kdenlive
Icon=zero-lliurex-kdenlive
Category=Software
ScriptPath=zero-lliurex-kdenlive.zmd
Groups=sudo;admins;teachers
Using=pkexec
#Service=True
#Modal=True
Show=True